# Generated by Django 4.0.3 on 2022-04-08 10:34

from django.db import migrations
from constants import ADMIN_GROUP_NAME


def create_group(apps, schema_editor):
    """
    Create admin group.
    """
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name=ADMIN_GROUP_NAME)


def delete_group(apps, schema_editor):
    """
    Create admin group.
    """
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name=ADMIN_GROUP_NAME).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_group, delete_group),
    ]
